### ISSUE TITLE
Add .ICO format and vector sources.

### ISSUE THREAD

**Issue by zizzo81** [DelphiClubItalia/IconSetFree#1]
.ICO format is a main requirement.
Icon vector sources (.SVG maybe?) would be a plus.
You can also think about generating a dedicated TTF file!

**Comment by DelphiClubItalia** [comment]
the ico format has been added. 
sorry but the svg is not in the roadmap :)

**Comment by zizzo81** [comment]
Ok, feel free to close this issue then.
